//nơi dùng để gửi yêu cầu tới server theo định dạng json
POST http://localhost:3000/signup
Content-Type: application/json

{
    "fullname":"lyngocan",
    "email":"lyngocan2222@gmail.com",
    "password":"Qwe97001@"
}