POST http://localhost:3000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmFlYzE0OGRlYWYxMDU1YmY1N2Y4MiIsImlhdCI6MTc2NDQyMDYyOSwiZXhwIjoxNzY0NDI0MjI5fQ.0EnlUfDkdKl_zYJICQ4g-T2s4t7_TLh-RY15aZqTiBc

{
    "title":"test title @ 3 134 # 4$ 123 asdas 12",
    "banner":"https://example.com/image-url",
    "des":"this is ashort des",
    "content": {
        "blocks":[1,2]
    },
    "tags":["tag1", "tag2"]
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk0MGY0MTk2NjVlZGE0NDM4MTJiNyIsImlhdCI6MTc2NDMxMTI4NCwiZXhwIjoxNzY0MzE0ODg0fQ.e7s7CNKvFCNEQjs25_pj9rKJobCn_dkwYorHWvfSupo

# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname":"jonh3",
#     "email":"nguyenhau112@gmail.com",
#     "password":"Nguyenhau112"

# }